# Generated by Django 4.1.6 on 2023-03-30 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scores', models.PositiveSmallIntegerField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
